version: '3.7'

services:
  url_db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  url_web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/dev_proj
      - static:/usr/src/dev_proj/static/
      - media:/usr/src/dev_proj/media/
    ports:
      - 8000:8000
    depends_on:
      - url_db
  nginx:
    build: ./nginx
    volumes:
      - static:/usr/src/dev_proj/static/
      - media:/usr/src/dev_proj/media/

    ports:
      - 80:80
      - 443:443
    depends_on:
      - url_db

volumes:
  postgres_data:
  static:
  media:
