version: '3.7'

services:
  url_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - static:/static
    ports:
       - 5432:5432
  url_web:
    build: .
    env_file:
      - .env
#    command: python /usr/src/dev_proj/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/dev_proj
    ports:
      - 8000:8000
    depends_on:
      - url_db
#  nginx:
#    build: ./nginx
#    volumes:
#      - static:/static
#    ports:
#      - 80:80
#    depends_on:
#      - url_db

volumes:
  postgres_data:
  static:
