version: '3.7'

services:
  url_db:
    image: postgres
    environment:
      - DARABASE=postgres
      - POSTGRES_DB=url_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
       - 5432:5432
  url_web:
    build: .
#    command: python /usr/src/dev_proj/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/dev_proj
    ports:
      - 8000:8000
    depends_on:
      - url_db

volumes:
  postgres_data:
  static:
